//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goflywin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("goflywin.Form-en-US", typeof(Form_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Console.
        /// </summary>
        internal static string buttonConsole {
            get {
                return ResourceManager.GetString("buttonConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Server.
        /// </summary>
        internal static string buttonDelServer {
            get {
                return ResourceManager.GetString("buttonDelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string buttonQuit {
            get {
                return ResourceManager.GetString("buttonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string buttonStart {
            get {
                return ResourceManager.GetString("buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string buttonStop {
            get {
                return ResourceManager.GetString("buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to systray when proxy started.
        /// </summary>
        internal static string checkAutoMin {
            get {
                return ResourceManager.GetString("checkAutoMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch goflywin at startup.
        /// </summary>
        internal static string checkAutostart {
            get {
                return ResourceManager.GetString("checkAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicitly log to &apos;log.txt&apos;.
        /// </summary>
        internal static string checkLogtxt {
            get {
                return ResourceManager.GetString("checkLogtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable man-in-the-middle.
        /// </summary>
        internal static string checkMITM {
            get {
                return ResourceManager.GetString("checkMITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial encryption.
        /// </summary>
        internal static string checkPartial {
            get {
                return ResourceManager.GetString("checkPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string groupAuth {
            get {
                return ResourceManager.GetString("groupAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Log.
        /// </summary>
        internal static string groupLog {
            get {
                return ResourceManager.GetString("groupLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string groupMisc {
            get {
                return ResourceManager.GetString("groupMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string labelAuthPass {
            get {
                return ResourceManager.GetString("labelAuthPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string labelAuthUser {
            get {
                return ResourceManager.GetString("labelAuthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS Cache.
        /// </summary>
        internal static string labelDNS {
            get {
                return ResourceManager.GetString("labelDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Domain.
        /// </summary>
        internal static string labelDomain {
            get {
                return ResourceManager.GetString("labelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string labelKey {
            get {
                return ResourceManager.GetString("labelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        internal static string labelLogLevel {
            get {
                return ResourceManager.GetString("labelLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please import &apos;ca.pem&apos; into the &apos;Trusted Root Certification Authority&apos; store first, then MITM can work properly..
        /// </summary>
        internal static string labelMITMNote {
            get {
                return ResourceManager.GetString("labelMITMNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Listen.
        /// </summary>
        internal static string labelPort {
            get {
                return ResourceManager.GetString("labelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Type.
        /// </summary>
        internal static string labelProxyType {
            get {
                return ResourceManager.GetString("labelProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address (IP:Port).
        /// </summary>
        internal static string labelServer {
            get {
                return ResourceManager.GetString("labelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server UDP.
        /// </summary>
        internal static string labelUDP {
            get {
                return ResourceManager.GetString("labelUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP over TCP.
        /// </summary>
        internal static string labelUDP_TCP {
            get {
                return ResourceManager.GetString("labelUDP_TCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy: iplist only|Proxy: global|Proxy: do not proxy.
        /// </summary>
        internal static string menuProxyType {
            get {
                return ResourceManager.GetString("menuProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show goflywin.
        /// </summary>
        internal static string menuShow {
            get {
                return ResourceManager.GetString("menuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure of deleting this server?.
        /// </summary>
        internal static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing params, please check: server address, local listen and key..
        /// </summary>
        internal static string msgPleaseCheckInput {
            get {
                return ResourceManager.GetString("msgPleaseCheckInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goflywin is minimized.
        /// </summary>
        internal static string msgSystray {
            get {
                return ResourceManager.GetString("msgSystray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT RUNNING.
        /// </summary>
        internal static string NOTRUNNING {
            get {
                return ResourceManager.GetString("NOTRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; RUNNING &lt;&lt;.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
    }
}
