//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goflywin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("goflywin.Form-zh-CN", typeof(Form_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开控制台.
        /// </summary>
        internal static string buttonConsole {
            get {
                return ResourceManager.GetString("buttonConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除服务器.
        /// </summary>
        internal static string buttonDelServer {
            get {
                return ResourceManager.GetString("buttonDelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string buttonQuit {
            get {
                return ResourceManager.GetString("buttonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        internal static string buttonStart {
            get {
                return ResourceManager.GetString("buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string buttonStop {
            get {
                return ResourceManager.GetString("buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理启动后最小化 goflywin.
        /// </summary>
        internal static string checkAutoMin {
            get {
                return ResourceManager.GetString("checkAutoMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开机启动 goflywin.
        /// </summary>
        internal static string checkAutostart {
            get {
                return ResourceManager.GetString("checkAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将日志写入“log.txt”.
        /// </summary>
        internal static string checkLogtxt {
            get {
                return ResourceManager.GetString("checkLogtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中间人代理模式.
        /// </summary>
        internal static string checkMITM {
            get {
                return ResourceManager.GetString("checkMITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半加密模式.
        /// </summary>
        internal static string checkPartial {
            get {
                return ResourceManager.GetString("checkPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 认证.
        /// </summary>
        internal static string groupAuth {
            get {
                return ResourceManager.GetString("groupAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        internal static string groupLog {
            get {
                return ResourceManager.GetString("groupLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string groupMisc {
            get {
                return ResourceManager.GetString("groupMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string labelAuthPass {
            get {
                return ResourceManager.GetString("labelAuthPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string labelAuthUser {
            get {
                return ResourceManager.GetString("labelAuthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS缓存.
        /// </summary>
        internal static string labelDNS {
            get {
                return ResourceManager.GetString("labelDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假域名.
        /// </summary>
        internal static string labelDomain {
            get {
                return ResourceManager.GetString("labelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密钥.
        /// </summary>
        internal static string labelKey {
            get {
                return ResourceManager.GetString("labelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志等级.
        /// </summary>
        internal static string labelLogLevel {
            get {
                return ResourceManager.GetString("labelLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为了使用中间人模式，请首先将“ca.pem”添加至“受信任的根证书”里。.
        /// </summary>
        internal static string labelMITMNote {
            get {
                return ResourceManager.GetString("labelMITMNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地监听.
        /// </summary>
        internal static string labelPort {
            get {
                return ResourceManager.GetString("labelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理类型.
        /// </summary>
        internal static string labelProxyType {
            get {
                return ResourceManager.GetString("labelProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器地址（IP:端口）.
        /// </summary>
        internal static string labelServer {
            get {
                return ResourceManager.GetString("labelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器UDP.
        /// </summary>
        internal static string labelUDP {
            get {
                return ResourceManager.GetString("labelUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP over TCP.
        /// </summary>
        internal static string labelUDP_TCP {
            get {
                return ResourceManager.GetString("labelUDP_TCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理：绕过中国|代理：全局|代理：不代理.
        /// </summary>
        internal static string menuProxyType {
            get {
                return ResourceManager.GetString("menuProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示 goflywin.
        /// </summary>
        internal static string menuShow {
            get {
                return ResourceManager.GetString("menuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认删除该服务器.
        /// </summary>
        internal static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缺少必要参数：服务器地址、本地监听地址、或密钥.
        /// </summary>
        internal static string msgPleaseCheckInput {
            get {
                return ResourceManager.GetString("msgPleaseCheckInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goflywin 已最小化至系统托盘.
        /// </summary>
        internal static string msgSystray {
            get {
                return ResourceManager.GetString("msgSystray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理尚未启动.
        /// </summary>
        internal static string NOTRUNNING {
            get {
                return ResourceManager.GetString("NOTRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; 代理中 &lt;&lt;.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
    }
}
