//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goflywin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("goflywin.Form-Resource", typeof(Form_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ca {
            get {
                object obj = ResourceManager.GetObject("ca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-6.com
        ///0-gold.net
        ///00.net
        ///0000738.com
        ///0001688.com
        ///000219.com
        ///0007.net
        ///000dn.com
        ///000e.com
        ///000w.net
        ///001-us.com
        ///001.tn
        ///00137.net
        ///001bank.com
        ///001ce.com
        ///001cndc.com
        ///001dianying.com
        ///001en.com
        ///001jm.com
        ///001job.com
        ///001pp.com
        ///001sxy.com
        ///001town.com
        ///001xin.com
        ///0027.net
        ///002dh.com
        ///0033.com
        ///003593.com
        ///00394.net
        ///005.tv
        ///00544.com
        ///0056.cc
        ///005789.cc
        ///00615.net
        ///006ky.com
        ///007.mx
        ///007gp.com
        ///007gxzt.com
        ///007shoes.com
        ///007swz.com
        ///007wr.com
        ///007yx.com
        ///008008.net
        ///00817.com
        ///0082tv.com
        ///0082tv. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chinalist {
            get {
                return ResourceManager.GetString("chinalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo_ZS6_icon {
            get {
                object obj = ResourceManager.GetObject("logo_ZS6_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
